[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npx serve dist -l $PORT"
healthcheckPath = "/"
restartPolicyType = "on_failure"

[nixpacks.variables]
NODE_VERSION = "22"
